name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.GOOGLE_CLOUD_SSH_KEY }}
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.GOOGLE_CLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "echo 'SSH works!'"
            cd /home/jasantise/HexaFront
            git pull origin main
            npm ci
            npm run build
            sudo cp -r dist/* /home/jasantise/HexaFront/dist
            sudo systemctl restart nginx
